// Generated by Selenium IDE
package es.upm.dit.isst.barriocovid;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import com.google.gson.*;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class FlujocompradorTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty( "webdriver.chrome.driver", "/home/marinaaretaasanza/Documentos/chromedriver_linux64/chromedriver");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void flujocomprador() {
    driver.get("http://localhost:8080/login");
    driver.manage().window().setSize(new Dimension(1853, 1053));
    driver.findElement(By.cssSelector(".form-signin")).click();
    driver.findElement(By.id("username")).sendKeys("Lucia Garcia");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("comprador1");
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.cssSelector(".col-lg-3:nth-child(4) .btn")).click();
    driver.findElement(By.id("cantidad")).sendKeys("2");
    driver.findElement(By.id("cantidad")).click();
    driver.findElement(By.cssSelector(".col-lg-3:nth-child(1) .btn")).click();
    driver.findElement(By.cssSelector(".col-lg-3:nth-child(2) .btn")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".col-lg-3:nth-child(2) .btn"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.xpath("//a[contains(@href, \'/verCarrito\')]")).click();
    driver.findElement(By.linkText("Siguiente")).click();
    driver.findElement(By.linkText("Confirmar pedido")).click();
    driver.findElement(By.linkText("PAGAR AHORA")).click();
    driver.findElement(By.id("navbarDropdownMenuLink")).click();
    driver.findElement(By.linkText("Cerrar sesión")).click();
    driver.findElement(By.cssSelector(".btn")).click();
  }
}
